### ISSUE TITLE
Suggest a multimodal dataset

### ISSUE THREAD

**Issue by repo-atvc** [zjr2000/Awesome-Multimodal-Assistant#1]
Thanks for the curated list of multimodal LLM. We have a related work that we hope is added to this awesome repository.

Accountable Textual-Visual Chat Learns to Reject Human Instructions in Image Re-creation (https://arxiv.org/pdf/2303.05983.pdf)

Project Page: https://matrix-alpha.github.io/

**Comment by zjr2000** [comment]
Thanks for your awesome work! We have included it to the list.

**Comment by zzw-zwzhang** [comment]
Appreciate.
